[phases.setup]
    nixPkgs = ['php82', 'php82Extensions.gd', 'php82Extensions.mysqlnd']

[phases.install]
    cmds = ['composer install --ignore-platform-reqs --optimize-autoloader --no-dev']

[start]
    cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'